repos:
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.1.1
  hooks:
    - id: mypy
      args: []
      additional_dependencies: [
        types-redis==4.5.1.5,
        types-setuptools==67.6.0.0,
        types-six==1.16.21.7,
      ]
